_default:
  @just --list
  @echo ""
  @echo "Run 'just <recipe>' to execute a task."

set working-directory := "../.."

# Download municipalities data and process it into GeoJSON.
download-municipalities:
  uv run python -m pipelines.extract.download_municipalities

# Convert downloaded GeoJSON files to the staging format.
geojson:
  uv run python -m pipelines.extract.geojson

# Download data from DE Wasserportal API.  Municipality data must be downloaded first.
# This will take several hours to complete and should not be run regularly so as to avoid hitting the API.
download-de-wasserportal:
  uv run python -m pipelines.extract.de_wasserportal