FROM python:3.12-slim

# tippecanoe build dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential libsqlite3-dev zlib1g-dev git && \
    git clone --depth 1 https://github.com/felt/tippecanoe.git /tmp/tippecanoe && \
    cd /tmp/tippecanoe && make -j && make install && \
    cd / && rm -rf /tmp/tippecanoe && \
    apt-get purge -y build-essential git && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

WORKDIR /app
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev

COPY pipelines/ ./pipelines/

ENV PM_TILES_DIR=/public/pmtiles
RUN mkdir -p /public/pmtiles

ENV EXPORT_IMAGES_DIR=/public/images
RUN mkdir -p /public/images

EXPOSE 3000

CMD ["uv", "run", "uvicorn", "pipelines.worker.app:app", "--host", "0.0.0.0", "--port", "3000"]
